
services:
  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001" # Porta per l'interfaccia di amministrazione
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_BROWSER_REDIRECT_URL: "${MINIO_BROWSER_REDIRECT_URL}"
      MINIO_SERVER_URL: "${MINIO_SERVER_URL}"
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  minio_data:
    driver: local
